# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "hugo-theme-geek"
license = "MIT"
licenselink = "https://github.com/wujunze/hugo-theme-geek/blob/master/LICENSE"
description = "A blog theme for hugo."
homepage = "https://wujunze.com"
tags = [
  "blog",
  "dark",
  "theme"
]
features = [
  "cover-image",
  "favicon",
  "multilingual",
  "pagination",
  "syntax-highlighting",
]
min_version = "0.41"

[author]
  name = "Panda"
  homepage = "https://wujunze.com"

# If porting an existing theme
[original]
  name = "Mogeko"
  homepage = "Mogeko"
